export const APP_CONFIG = {
  SUPABASE_URL: "COLE_AQUI_SUA_SUPABASE_URL",
  SUPABASE_ANON_KEY: "COLE_AQUI_SUA_SUPABASE_ANON_KEY",
  STORE_SLUG: "minha-loja",
  PUBLIC_VAPID_KEY: "COLE_AQUI_SUA_PUBLIC_VAPID_KEY",
  APP_NAME: "VitrineZap"
};
